# Generated by Django 6.0 on 2025-12-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
    ]
