# Generated by Django 6.0 on 2025-12-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True, help_text="Progress notes and updates"),
        ),
    ]
